image: node:16

pipelines:
  branches:
    master:
      - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              - npm test
              - apt update && apt install zip
              # Exclude files to be ignored
              - zip -r app.zip . -x *.git* bitbucket-pipelines.yml
            artifacts:
              - "app.zip"
      - step:
          name: Deploy to Production
          trigger: manual
          deployment: Production
          script:
            - pipe: atlassian/azure-web-apps-deploy:1.1.0
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                AZURE_RESOURCE_GROUP: $AZURE_RESOURCE_GROUP
                AZURE_APP_NAME: $AZURE_APP_NAME
                ZIP_FILE: app.zip
